---CREATE DOCKERFILE FILE---
Dockerfile 

---COMMAND FOR THE EXECUTION AND CREATION OF FILE: DOCKERFILE---
docker build -t <NAME_YOUR_IMAGE> .

---CREATE OF CONTAINER THROUGH IMAGEM AND CREATE NAME AND EXECUTATION IN BACKGROUND OF CONTAINER---
docker container run -d --name <NAME_CONTAINER> <ID_IMAGE>

---EXAMPLE BASIC OF INSTRUCTION OF A DOCKERFILE---
FROM ubuntu
RUN apt-get update
RUM apt-get install git --yes

---DETAILS INSTRUCTION OF THE DOCKERFILE---
FROM: Initial point. Select your image for workflow.
Example: FROM ubuntu; FROM nginx; FROM node

RUN: Execute from process of mount image.

WORKDIR:

CMD:

EXPOSE:

COPY and ADD:

VOLUME:

USER: